apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: alerts-exporter
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: alerts-exporter-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: alerts-exporter
    app.kubernetes.io/part-of: alerts-exporter
    app.kubernetes.io/managed-by: kustomize
  name: alerts-exporter-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: alerts-exporter
