apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: exporter-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: alerts-exporter
    app.kubernetes.io/part-of: alerts-exporter
    app.kubernetes.io/managed-by: kustomize
  name: exporter-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exporter-role
subjects:
- kind: ServiceAccount
  name: alerts-exporter
