apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: alerts-exporter
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: alerts-exporter
    app.kubernetes.io/part-of: alerts-exporter
    app.kubernetes.io/managed-by: kustomize
  name: alerts-exporter
