apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-collector
spec:
  selector:
    matchLabels:
      app: alerts-collector
  template:
    metadata:
      labels:
        app: alerts-collector
    spec:
      containers:
        - name: collector
          image: local.dev/alerts-collector:latest
          resources:
            resources:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
